### ISSUE TITLE
go run main.go 

### ISSUE THREAD

**Issue by rainbow2019s** [xhaoxiong/irisgo#16]
web\middleware\jwt.go:17:2: cannot use extractor (type func("github.com/kataras/iris/v12/context".Context) (string, error)) as type "github.com/iris-contrib/middleware/jwt".TokenExtractor in field value
web\middleware\jwt.go:47:3: cannot use func literal (type func("github.com/kataras/iris/v12/context".Context, error)) as type "github.com/iris-contrib/middleware/jwt".errorHandler in field value
is go1.15 too high?

**Comment by xhaoxiong** [comment]
我已经重新修复了

**Comment by xhaoxiong** [comment]
是jwt基础接口变动了

**Comment by lgy87** [comment]
谢谢作者的工作成果。我执行 go run main.go 时 报如下的错误。

go/pkg/mod/github.com/casbin/gorm-adapter/v3@v3.0.3/adapter.go:247:25: unknown field 'WithConditions' in struct literal of type gorm.Session

@xhaoxiong
